version: 2.1
jobs:
  build:
    working_directory: ~/code-reviewewr
    docker:
      - image: circleci/node:12.11
    steps:
      - checkout
      - run:
        name: update-npm
        command: 'sudo npm install -g npm@latest'
      - run:
        name: update-npm
        command: 'sudo rm -rf ~/.yarn && npm install -g yarn'