version: 2.1
jobs:
  build:
    working_directory: ~/code-reviewer
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout

      - restore_cache:
          keys:
            - node-v1-{{ checksum "package.json" }}-{{ checksum "yarn.lock" }}

      - run: yarn --frozen-lockfile

      - run: 
          command: yarn autoclean --force

      - save_cache:
          paths:
            - node_modules
            - ~/.yarn 
            - ~/.config/yarn
          key: node-v1-{{ checksum "package.json" }}-{{ checksum "yarn.lock" }}

      # Run tests
      - run:
          name: test
          command: yarn test

      # Run Lints
      - run:
          name: lint
          command: yarn lint

      # Run build on packages/client
      - run:
          name: lint
          command: yarn build:client