version: 2.1
jobs:
  build:
    working_directory: ~/code-reviewewr
    docker:
      - image: circleci/node:12.11
    steps:
      - checkout
      - restore_cache:
        name: Restore Yarn package cache
        keys:
          - yarn-packages-{{ checksum "yarn.lock" }}
